name: Update README

on: 
  workflow_dispatch:
  schedule: 
    - cron: "0 */1 * * *"
  push: 
    branches: 
      - "main"

jobs:
  markgen: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@main

      - uses: JosueIsOffline/readme-generate-action@main
        env: 
          GITHUB_TOKEN: ${{secrets.PERSONAL_GITHUB_TOKEN}}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          commit_message: "chore: update generated README"
          branch: main
          commit_user_name: JosueIsOffline
          commit_user_email: josuehernandez2314@gmail.com
          commit_author: JosueIsOffline <josuehernandez2314@gmail.com>
