name: Update README

on: 
  workflow_dispatch:
  schedule: 
    - cron: "0 */1 * * *"
  push: 
    branches: 
      - "main"

jobs:
  markgen: 
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps: 
      - uses: actions/checkout@v4 

      - uses: JosueIsOffline/readme-gerenerate-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: update generated README"
          commit_user_name: JosueIsOffline
          commit_user_email: josuehernandez2314@gmail.com
          commit_author: JosueIsOffline <josuehernandez2314@gmail.com>
